module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
    MAIN_PAGE_SELECT_SUCCESS: "메인 이미지 조회 성공",
    WEBTOON_INSERT_SUCCESS: "웹툰 작성 성공",
    WEBTOON_INSERT_FAIL: "웹툰 작성 실패",
    WEBTOON_SELECT_FAIL: "웹툰 조회 실패",
    WEBTOON_SELECT_SUCCESS: "웹툰 조회 성공",
    EPISODE_INSERT_FAIL: "에피소드 삽입 실패",
    EPISODE_INSERT_SUCCESS: "에피소드 삽입 성공",
    EPISODE_SELECT_FAIL: "에피소드 조회 실패",
    EPISODE_SELECT_SUCCESS: "에피소드 조회 성공",
    EPISODE_TRANS_SUCCESS: "에피소드 트랜젝션 성공",
    EPISODE_TRANS_FAIL: "에피소드 트랜젝션 실패",
    COMMENT_INSERT_FAIL: "댓글 삽입 실패",
    COMMENT_INSERT_SUCCESS: "댓글 삽입 성공",
    COMMENT_SELECT_FAIL: "댓글 조회 실패",
    COMMENT_SELECT_SUCCESS: "댓글 조회 성공",
    LOGIN_FAIL: "로그인 실패",
    LOGIN_SUCCESS: "로그인 성공",
    USER_INSERT_SUCCESS: "회원가입 성공",
    USER_INSERT_FAIL: "회원가입 실패",
    USER_SELECT_FAIL: "유저 조회 실패",
    USER_ALREADY_EXISTS: "이미 존재하는 유저입나다",
    ID_MISS_MATCH: "아이디가 존재하지 않습니다.",
    PASSWORD_MISS_MATCH: "패스워드가 일치하지 않습니다."
};